config/routes.rb
Rails.application.routes.draw do
  resources :replies,only:[:create,:edit,:update,:destroy]
  resources :comments,only:[:create,:edit,:update,:destroy]
  resources :answers,only:[:create,:edit,:update,:destroy]
  resources :questions,only:[:create,:edit,:update,:destroy]
  get 'home/index'
  root 'home#index'
  get '/profile' =>'home#profile'
  get '/users' =>'home#users'
  post'/upload'=> 'home#profile_picture'
  post '/upvoteToggle' => 'upvoteqs#upvoteToggle'
  post '/downvoteToggle' => 'downvoteqs#downvoteToggle'
  post '/upvoteToggleAnswer' => 'upvoteas#upvoteToggleAnswer'
  post '/downvoteToggleAnswer' => 'downvoteas#downvoteToggleAnswer'
  post '/upvoteToggleComment' => 'upvotecs#upvoteToggleComment'
  post '/downvoteToggleComment' => 'downvotecs#downvoteToggleComment'
  post '/upvoteToggleReply' => 'upvoters#upvoteToggleReply'
  post '/downvoteToggleReply' => 'downvoters#downvoteToggleReply'
  post '/follow' => 'home#follow'
  devise_for :users

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
  validates :content, presence: true
  has_many :upvoters, dependent: :destroy
  has_many :downvoters, dependent: :destroy
def upvote_reply user_id
    Upvoter.where(reply_id: id, user_id: user_id).length > 0
  end
  def classStringReply user_id
    if upvote_reply user_id
      return "upvoted"
    else
      return "notupvoted"
    end
  end


  def downvote_Reply user_id
    Downvoter.where(reply_id: id, user_id: user_id).length > 0
  end
  def classStringReplyDownvote user_id
    if downvote_Reply user_id
      return "downvoted"
    else
      return "notdownvoted"
    end
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :set_reply, only: [:show, :edit, :update, :destroy]

  # GET /replies
  # GET /replies.json
  def index
    @replies = Reply.all
  end

  # GET /replies/1
  # GET /replies/1.json
  def show
  end

  # GET /replies/new
  def new
    @reply = Reply.new
  end

  # GET /replies/1/edit
  def edit
  end

  # POST /replies
  # POST /replies.json
  def create
    @reply = Reply.new(reply_params)

    respond_to do |format|
      if @reply.save
        format.html { redirect_to '/', notice: 'Reply was successfully created.' }
        format.json { render :show, status: :created, location: @reply }
        format.js{ }
      else
        format.html { render :new }
        format.js{ }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /replies/1
  # PATCH/PUT /replies/1.json
  def update
    respond_to do |format|
      if @reply.update(reply_params)
        format.html { redirect_to @reply, notice: 'Reply was successfully updated.' }
        format.json { render :show, status: :ok, location: @reply }
      else
        format.html { render :edit }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /replies/1
  # DELETE /replies/1.json
  def destroy
    @reply.destroy
    respond_to do |format|
      format.html { redirect_to '/', notice: 'Reply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reply
      @reply = Reply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reply_params
      params.require(:reply).permit(:content, :user_id, :comment_id)
    end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_form.html.erb
<%= form_for(@reply) do |f| %>
  <% if @reply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reply.errors.count, "error") %> prohibited this reply from being saved:</h2>

      <ul>
      <% @reply.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :comment_id %><br>
    <%= f.text_field :comment_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/replies/create.js.erb
<%if @reply.errors.any?%>
noty({text: "<%=@reply.errors.full_messages.first%>",type: 'error', timeout: 1000});
<%else%>
console.log("here")
$('#allReplies_<%=@reply.comment.id%>').prepend("<%= escape_javascript (render 'home/reply', reply: @reply)%>");
$('#reply_content_<%=@reply.comment.id%>').val("");
noty({text: 'comment has been successfully replied!!', type: 'success', timeout: 1000});
<%end%>

app/views/replies/edit.html.erb
<h1>Editing Reply</h1>

<%= render 'form' %>

<%= link_to 'Show', @reply %> |
<%= link_to 'Back', replies_path %>

app/views/replies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Replies</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @replies.each do |reply| %>
      <tr>
        <td><%= reply.content %></td>
        <td><%= reply.user %></td>
        <td><%= reply.comment %></td>
        <td><%= link_to 'Show', reply %></td>
        <td><%= link_to 'Edit', edit_reply_path(reply) %></td>
        <td><%= link_to 'Destroy', reply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reply', new_reply_path %>

app/views/replies/new.html.erb
<h1>New Reply</h1>

<%= render 'form' %>

<%= link_to 'Back', replies_path %>

app/views/replies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @reply.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @reply.user %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @reply.comment %>
</p>

<%= link_to 'Edit', edit_reply_path(@reply) %> |
<%= link_to 'Back', replies_path %>