config/routes.rb
Rails.application.routes.draw do
  resources :replies,only:[:create,:edit,:update,:destroy]
  resources :comments,only:[:create,:edit,:update,:destroy]
  resources :answers,only:[:create,:edit,:update,:destroy]
  resources :questions,only:[:create,:edit,:update,:destroy]
  get 'home/index'
  root 'home#index'
  get '/profile' =>'home#profile'
  get '/users' =>'home#users'
  post'/upload'=> 'home#profile_picture'
  post '/upvoteToggle' => 'upvoteqs#upvoteToggle'
  post '/downvoteToggle' => 'downvoteqs#downvoteToggle'
  post '/upvoteToggleAnswer' => 'upvoteas#upvoteToggleAnswer'
  post '/downvoteToggleAnswer' => 'downvoteas#downvoteToggleAnswer'
  post '/upvoteToggleComment' => 'upvotecs#upvoteToggleComment'
  post '/downvoteToggleComment' => 'downvotecs#downvoteToggleComment'
  post '/upvoteToggleReply' => 'upvoters#upvoteToggleReply'
  post '/downvoteToggleReply' => 'downvoters#downvoteToggleReply'
  post '/follow' => 'home#follow'
  devise_for :users

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  has_many :upvoteas, dependent: :destroy
  has_many :downvoteas, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :content, presence: true
  validates :user, presence: true

  def upvote_answer user_id
    Upvotea.where(answer_id: id, user_id: user_id).length > 0
  end
  def classStringAnswer user_id
    if upvote_answer user_id
      return "upvoted"
    else
      return "notupvoted"
    end
  end


  def downvote_answer user_id
    Downvotea.where(answer_id: id, user_id: user_id).length > 0
  end
  def classStringAnswerDownvote user_id
    if downvote_answer user_id
      return "downvoted"
    else
      return "notdownvoted"
    end
  end



end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :answer
  has_many :upvotecs, dependent: :destroy
  has_many :replies, dependent: :destroy
  has_many :downvotecs, dependent: :destroy
  validates :content, presence: true
  validates :user, presence: true
def upvote_comment user_id
    Upvotec.where(comment_id: id, user_id: user_id).length > 0
  end
  def classStringComment user_id
    if upvote_comment user_id
      return "upvoted"
    else
      return "notupvoted"
    end
  end


  def downvote_comment user_id
    Downvotec.where(comment_id: id, user_id: user_id).length > 0
  end
  def classStringCommentDownvote user_id
    if downvote_comment user_id
      return "downvoted"
    else
      return "notdownvoted"
    end
  end
end

app/models/downvotea.rb
class Downvotea < ActiveRecord::Base
  belongs_to :user
  belongs_to :answer
  validates :user, presence: true
  validates :answer, presence: true
  validates_uniqueness_of :user, :scope => :answer
end

app/models/downvotec.rb
class Downvotec < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
  validates :user, presence: true
  validates :comment, presence: true
  validates_uniqueness_of :user, :scope => :comment
end

app/models/downvoteq.rb
class Downvoteq < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  validates :user, presence: true
  validates :question, presence: true
  validates_uniqueness_of :user, :scope => :question
end

app/models/downvoter.rb
class Downvoter < ActiveRecord::Base
  belongs_to :user
  belongs_to :reply
  validates :user, presence: true
  validates :reply, presence: true
  validates_uniqueness_of :user, :scope => :reply
end

app/models/follow_mapping.rb
class FollowMapping < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
   has_many :answers, dependent: :destroy
   has_many :upvoteqs, dependent: :destroy
   has_many :downvoteqs, dependent: :destroy
  validates :content, presence: true
  validates :user, presence: true

  def upvote_question user_id
  	Upvoteq.where(question_id: id, user_id: user_id).length > 0
  end
  def classStringQuestion user_id
  	if upvote_question user_id
  		return "upvoted"
  	else
  		return "notupvoted"
  	end
  end


  def downvote_question user_id
  	Downvoteq.where(question_id: id, user_id: user_id).length > 0
  end
  def classStringQuestionDownVote user_id
  	if downvote_question user_id
  		return "downvoted"
  	else
  		return "notdownvoted"
  	end
  end


end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
  validates :content, presence: true
  has_many :upvoters, dependent: :destroy
  has_many :downvoters, dependent: :destroy
def upvote_reply user_id
    Upvoter.where(reply_id: id, user_id: user_id).length > 0
  end
  def classStringReply user_id
    if upvote_reply user_id
      return "upvoted"
    else
      return "notupvoted"
    end
  end


  def downvote_Reply user_id
    Downvoter.where(reply_id: id, user_id: user_id).length > 0
  end
  def classStringReplyDownvote user_id
    if downvote_Reply user_id
      return "downvoted"
    else
      return "notdownvoted"
    end
  end
end

app/models/upvotea.rb
class Upvotea < ActiveRecord::Base
  belongs_to :user
  belongs_to :answer
  validates :user, presence: true
  validates :answer, presence: true
  validates_uniqueness_of :user, :scope => :answer
end

app/models/upvotec.rb
class Upvotec < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
	validates :user, presence: true
  validates :comment, presence: true
  validates_uniqueness_of :user, :scope => :comment
end

app/models/upvoteq.rb
class Upvoteq < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  validates :user, presence: true
  validates :question, presence: true
  validates_uniqueness_of :user, :scope => :question
end

app/models/upvoter.rb
class Upvoter < ActiveRecord::Base
  belongs_to :user
  belongs_to :reply
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    validates :firstName,presence: true
    validates :lastName,presence: true
	has_many :questions, dependent: :destroy
	has_many :answers,   dependent: :destroy
	has_many :replies,   dependent: :destroy
	has_many :upvoteqs,  dependent: :destroy
	has_many :upvoteas,  dependent: :destroy
	has_many :upvotecs,  dependent: :destroy
	has_many :upvoters,  dependent: :destroy
	has_many :comments,  dependent: :destroy
	has_many :downvoteqs,dependent: :destroy
	has_many :downvoteas,dependent: :destroy
	has_many :downvotecs,dependent: :destroy
	has_many :downvoters,dependent: :destroy
	has_many :comments,  dependent: :destroy
  	has_many :replies,   dependent: :destroy
	def followings
		User.find(FollowMapping.where(follower_id: id).pluck(:followee_id))
	end
	def followers
		User.find(FollowMapping.where(followee_id: id).pluck(:follower_id))
	end
	def followed followee_id,follower_id
		
		f = FollowMapping.where(follower_id: follower_id,followee_id: followee_id).first
		if f
			return "unfollow"
		else
			return "follow"
		end
	end
	enum post: {reader: 0, member: 1, moderator: 2, admin: 3}     
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
     
  	respond_to do |format|
  		format.html{
  			@question=Question.new
  			@question_feed=Question.all.order(created_at: :desc)
  			@answer=Answer.new
  			@answer_feed=Answer.all.order(created_at: :desc)
  		}
  		format.js{   }	
  	end
  end
  def profile
    @user = User.find params[:user]

  end
  def profile_picture
    uploaded_file = params[:image]
    if uploaded_file==nil
      return redirect_to '/profile'
    end
    filename = SecureRandom.hex + "." +uploaded_file.original_filename.split('.')[1]
    filepath = Dir.pwd + "/public/uploads/" + filename
    File.open(filepath,'wb') do |file|
    file.write(uploaded_file.read())
    end
    current_user.profile_picture = filename
    current_user.save
    return redirect_to '/profile'
  end

def follow
  followee_id = params[:followee_id]
  @followee = User.find(followee_id)
  follower_id = current_user.id
  @follower = User.find(follower_id)
  
  f = FollowMapping.where(follower_id: follower_id,followee_id: followee_id).first
  if f
    f.destroy
  elsif followee_id.to_i != follower_id.to_i
    f = FollowMapping.new
    f.follower_id = follower_id
    f.followee_id = followee_id
    f.save
  end
 respond_to do |format|
    format.html{
       return redirect_to '/users'
    }
    format.js{ }
  end
end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/upvoteas_helper.rb
module UpvoteasHelper
end

app/helpers/upvotecs_helper.rb
module UpvotecsHelper
end

app/helpers/upvoteqs_helper.rb
module UpvoteqsHelper
end

app/views/home/_answer.html.erb
	<div class="answerShow">
		<div class="answerHeader">
			<div class="user">
				<div class="left">
					<% if answer.user.profile_picture %>
						<img src="/uploads/<%= answer.user.profile_picture %>" class="profile_image" >
					<%else%>
						<img src="/uploads/twitter-default-no-profile-pic.jpg" class="profile_image" >
					<% end %>
				</div>
				<div class = "right">
					answered by <%=answer.user.firstName%> <%=answer.user.lastName%>
					on <%=answer.created_at.strftime("%b %d,%y")%>
				</div>
			</div>

			<%if current_user %> 
					<%if answer.user == current_user || User.posts[current_user.post]>=2 %> 
						<div class="allbuttonthings">
							<span id = "button_answer_<%=answer.id%>" style="cursor:pointer"><h1>...</h1></span>	
							<div class="dropDown" id="drop_answer_<%=answer.id%>" >
									<ol>
									 <li><%=link_to "edit",edit_answer_path(id: answer.id),method: :get%></li>
									 <li><%= link_to "delete",answer_path(id: answer.id),method: :delete,data: {confirm:"Are 		you sure?"}%></li>
									 </ol>
							</div>
						</div>
					<%end%>
				<%end%>
		</div>
			<script type="text/javascript">
			function dropDown(){
				drop = document.getElementById("drop_answer_<%=answer.id%>");
				console.log(drop.style.display)
				if (drop.style.display == 'none'|| drop.style.display == ''){
					drop.style.display = 'block'
				}
				else{
					drop.style.display = 'none'
				}
			
			}
			button = document.getElementById("button_answer_<%=answer.id%>");
			button.addEventListener('click',dropDown);
			</script>
		<span id="content"><%=answer.content%> </span>
		<br><br>
<% if current_user != nil%>

		<%= link_to 'Upvote', url_for(controller: 'upvoteas', action: 'upvoteToggleAnswer', answer: answer.id), method: :post,id: "upvote_answer_#{answer.id}", remote: true, class: answer.classStringAnswer(current_user.id)%>   <span id="upcount_answer_<%=answer.id%>"><%= answer.upvoteas.count %></span>

		<%= link_to 'Downvote', url_for(controller: 'downvoteas', action: 'downvoteToggleAnswer', answer: answer.id), method: :post,id: "downvote_answer_#{answer.id}",remote: true, class: answer.classStringAnswerDownvote(current_user.id) %>   <span id="downcount_answer_<%=answer.id%>"><%= answer.downvoteas.count %></span>
		<%end%>
		<br><br>
<% if current_user != nil%>
		<div id="createComment">
			<%@comment=Comment.new%>
				 <%= form_for @comment, remote: true do |f|%>
					 <%= f.label :comment %> <br>
					 <%= f.text_area :content,id:  "comment_content_#{answer.id}"%>  <br>
				  	 <%= f.hidden_field :answer_id, :value => answer.id %>
					 <%=f.hidden_field :user_id, :value => current_user.id %>
					 <%= f.submit value:"Comment" ,id:  'create-comment-submit'%>
			 	 <%end%>
		</div>
<%end%>
		<% comments = Comment.where(answer_id: answer.id).order(created_at: :desc)%>
			<div id="allComments_<%=answer.id%>" class="allComments">
				 <%  comments.each do |comment| %><br>
					 <%=render 'comment',answer: answer,comment: comment%>
				 <%end%>
			</div>

</div>

app/views/home/_comment.html.erb
	<div class="commentShow">
		<div class="commentHeader">
			<div class="user">
				<div class="left">
					<% if comment.user.profile_picture %>
						<img src="/uploads/<%= comment.user.profile_picture %>" class="profile_image" >
					<%else%>
						<img src="/uploads/twitter-default-no-profile-pic.jpg" class="profile_image" >
					<% end %>
				</div>
				<div class = "right">
					commented by <%=comment.user.firstName%> <%=comment.user.lastName%>
					on <%=comment.created_at.strftime("%b %d,%y")%>
				</div>
			</div>

			<%if current_user %> 
					<%if comment.user == current_user || User.posts[current_user.post]>=2 %> 
						<div class="allbuttonthings">
							<span id = "button_comment_<%=comment.id%>" style="cursor:pointer"><h1>...</h1></span>	
							<div class="dropDown" id="drop_comment_<%=comment.id%>" >
									<ol>
									 <li><%=link_to "edit",edit_comment_path(id: comment.id),method: :get%></li>
									 <li><%= link_to "delete",comment_path(id: comment.id),method: :delete,data: {confirm:"Are 		you sure?"}%></li>
									 </ol>
							</div>
						</div>
					<%end%>
				<%end%>
		</div>
			<script type="text/javascript">
			function dropDown(){
				drop = document.getElementById("drop_comment_<%=comment.id%>");
				console.log(drop.style.display)
				if (drop.style.display == 'none'|| drop.style.display == ''){
					drop.style.display = 'block'
				}
				else{
					drop.style.display = 'none'
				}
			
			}
			button = document.getElementById("button_comment_<%=comment.id%>");
			button.addEventListener('click',dropDown);
			</script>
		<%=comment.content%> 
		<br><br>
<% if current_user != nil%>
		<%= link_to 'Upvote', url_for(controller: 'upvotecs', action: 'upvoteToggleComment', comment: comment.id), method: :post,id: "upvote_comment_#{comment.id}", remote: true, class: comment.classStringComment(current_user.id)%>   <span id="upcount_comment_<%=comment.id%>"><%= comment.upvotecs.count %></span>

		<%= link_to 'Downvote', url_for(controller: 'downvotecs', action: 'downvoteToggleComment', comment: comment.id), method: :post,id: "downvote_comment_#{comment.id}",remote: true, class: comment.classStringCommentDownvote(current_user.id) %>   <span id="downcount_comment_<%=comment.id%>"><%= comment.downvotecs.count %></span>
<%end%>
		<br><br>
<% if current_user != nil%>
		<div id="createReply">
			<%@reply=Reply.new%>
				 <%= form_for @reply, remote: true do |f|%>
					 <%= f.label :reply %> <br>
					 <%= f.text_area :content,id:  "reply_content_#{comment.id}"%>  <br>
				  	 <%= f.hidden_field :comment_id, :value => comment.id %>
					 <%=f.hidden_field :user_id, :value => current_user.id %>
					 <%= f.submit value:"Reply" ,id:  'create-reply-submit'%>
			 	 <%end%>
		</div>
<%end%>
		<% replies = Reply.where(comment_id: comment.id).order(created_at: :desc)%>
			<div id="allReplies_<%=comment.id%>" class="allReplies">
				 <%  replies.each do |reply| %><br>
					 <%=render 'reply',reply: reply,reply: reply%>
				 <%end%>
			</div>
</div>

app/views/home/_question.html.erb
	<div class="questionShow">
			<div>
			<div class="buttonFlex">
					asked by <%=question.user.firstName%> <%=question.user.lastName%> 
					on <%=question.created_at.strftime("%b %d,%y")%>
						
				<%if current_user %> 
					<%if question.user == current_user || User.posts[current_user.post]>=2 %> 
						<div class="allbuttonthings">
							<span id = "button_question_<%=question.id%>" style="cursor:pointer"><h1>...</h1></span>	
						<div class="dropDown" id="drop_question_<%=question.id%>" >
							<ol>
							 <li><%=link_to "edit",edit_question_path(id: question.id),method: :get%></li>
							 <li><%= link_to "delete",question_path(id: question.id),method: :delete,data: {confirm:"Are 		you sure?"}%></li>
							 </ol>
						 </div>
						</div>
					<%end%>
				<%end%>
			</div>
			<script type="text/javascript">
			function dropDown(){
				drop = document.getElementById("drop_question_<%=question.id%>");
				console.log(drop.style.display)
				if (drop.style.display == 'none'|| drop.style.display == ''){
					drop.style.display = 'block'
				}
				else{
					drop.style.display = 'none'
				}
			
			}
			button = document.getElementById("button_question_<%=question.id%>");
			button.addEventListener('click',dropDown);
			</script>





			<h1><b><%=question.content%></b></h1>
			</div>
			
<%if current_user%>
			<br>

			<%= link_to 'Upvote', url_for(controller: 'upvoteqs', action: 'upvoteToggle', question: question.id), method: :post,id: "upvote_question_#{question.id}", remote: true, class: question.classStringQuestion(current_user.id) %>   <span id="upcount_question_<%=question.id%>"><%= question.upvoteqs.count %></span>

			<%= link_to 'Downvote', url_for(controller: 'downvoteqs', action: 'downvoteToggle', question: question.id), method: :post,id: "downvote_question_#{question.id}",remote: true, class: question.classStringQuestionDownVote(current_user.id) %>   <span id="downcount_question_<%=question.id%>"><%= question.downvoteqs.count %></span>

			<br><br>
<%end%>
<% if current_user != nil%>

			<div id="createAnswer">
			<%@answer=Answer.new%>
				 <%= form_for @answer, remote: true do |f|%>
					 <%= f.label :Answer %> <br>
					 <%= f.text_area :content,id:  "answer_content_#{question.id}"%>  <br>
				  	 <%= f.hidden_field :question_id, :value => question.id %>
					 <%=f.hidden_field :user_id, :value => current_user.id %>
					 <%= f.submit value:"Answer" ,id:  'create-answer-submit'%>
			 	 <%end%>
			</div>
<%end%>
			<% answers = Answer.where(question_id: question.id).order(created_at: :desc)%>
			<div id="allAnswers_<%=question.id%>" class="allAnswers">
				 <%  answers.each do |answer| %><br>
					 <%=render 'answer',question: question,answer: answer%>
				 <%end%>
			</div>


		</div>
		<style type="text/css">
			.fa-ellipsis-h{
				font-size:20px;
			}
		</style>

app/views/home/_reply.html.erb
	<div class="replyShow">
		<div class="replyHeader">
			<div class="user">
				<div class="left">
					<% if reply.user.profile_picture %>
						<img src="/uploads/<%= reply.user.profile_picture %>" class="profile_image" >
					<%else%>
						<img src="/uploads/twitter-default-no-profile-pic.jpg" class="profile_image" >
					<% end %>
				</div>
				<div class = "right">
					replyed by <%=reply.user.firstName%> <%=reply.user.lastName%>
					on <%=reply.created_at.strftime("%b %d,%y")%>
				</div>
			</div>

			<%if current_user %> 
					<%if reply.user == current_user || User.posts[current_user.post]>=2 %> 
						<div class="allbuttonthings">
							<span id = "button_reply_<%=reply.id%>" style="cursor:pointer"><h1>...</h1></span>	
							<div class="dropDown" id="drop_reply_<%=reply.id%>" >
									<ol>
									 <li><%=link_to "edit",edit_reply_path(id: reply.id),method: :get%></li>
									 <li><%= link_to "delete",reply_path(id: reply.id),method: :delete,data: {confirm:"Are 		you sure?"}%></li>
									 </ol>
							</div>
						</div>
					<%end%>
				<%end%>
		</div>
			<script type="text/javascript">
			function dropDown(){
				drop = document.getElementById("drop_reply_<%=reply.id%>");
				console.log(drop.style.display)
				if (drop.style.display == 'none'|| drop.style.display == ''){
					drop.style.display = 'block'
				}
				else{
					drop.style.display = 'none'
				}
			
			}
			button = document.getElementById("button_reply_<%=reply.id%>");
			button.addEventListener('click',dropDown);
			</script>
		<%=reply.content%> 
		<br><br>
<% if current_user != nil%>
		<%= link_to 'Upvote', url_for(controller: 'upvoters', action: 'upvoteToggleReply', reply: reply.id), method: :post,id: "upvote_reply_#{reply.id}", remote: true, class: reply.classStringReply(current_user.id)%>   <span id="upcount_reply_<%=reply.id%>"><%= reply.upvoters.count %></span>

		<%= link_to 'Downvote', url_for(controller: 'downvoters', action: 'downvoteToggleReply', reply: reply.id), method: :post,id: "downvote_reply_#{reply.id}",remote: true, class: reply.classStringReplyDownvote(current_user.id) %>   <span id="downcount_reply_<%=reply.id%>"><%= reply.downvoters.count %></span>
<%end%>	
</div>

app/views/home/follow.js.erb
console.log("#follow_<%=@followee.id%>");
console.log("<%=@followee.followed(@followee.id,@follower.id)%>");
console.log("<%=@followee.followers.length%>")
$("#follow_<%=@followee.id%>").text("<%=@followee.followed(@followee.id,@follower.id)%>");
$("#followings_<%=@follower.id%>").text("<%=@follower.followings.length%>");
$("#followers_<%=@followee.id%>").text("<%=@followee.followers.length%>");

app/views/home/index.html.erb
<main>
<section>
<% if current_user != nil%>
	<div id="createQuestion">
	<%= form_for @question ,remote: true do |f|%>
	<%= f.label :Ask_question %> <br>
	<%= f.text_area :content%>  <br>
	<%= f.submit  value:"Ask question", id:  'create-question-submit'%>
	<%end%>
	</div>
	<% if @question.errors.any? %>
        		<% @question.errors.full_messages.each do |message| %>
   				<script type="text/javascript">
				noty({text: '<%= message %>', type: 'error'});
				</script>
     		<% end %>
 	<% end %>
<%end%>
 	<div id="allQuestions">
	<%  @question_feed.each do |question| %><br>
			<%=render('question',question: question)%>
 	<%end%>

 	</div>

</section>

</main>

app/views/home/profile.html.erb
<main class="profile">
<div class="flex">
	<div class="left">
		<% if @user.profile_picture %>
			<img src="/uploads/<%= @user.profile_picture %>" class="profile_image" >
		<%else%>
			<img src="/uploads/twitter-default-no-profile-pic.jpg" class="profile_image" >
		<% end %>
		<% if @user == current_user%>
		<%= form_tag url_for(controller: :home, action: :profile_picture), multipart: true do %>

		<%= file_field_tag :image %>
		<br>
		<%= submit_tag %>

		<% end %>
		<%end%>
	</div>
	<div class="right">
	<h2> <%= @user.firstName%> <%= @user.lastName%> </h2>
	</div>
	
</div>
<% a = @user.answers.order(created_at: :desc)%>
<%if a.length == 0%>
<div class="allAnswers">
<h3>U haven't answered any question yet!!</h3>
</div>
<%else%>
<div class="allAnswers">
	<h3><span><%=a.length%> question answered by 
	<%if current_user == @user%>
	you
	<%else%>
	<%=@user.firstName%>
	<%end%>
	 </span></h3>
	<% a.each do |answer|%>
	<div class="answerShow">
		<div class="user">
		<div class="leftpic">
			<% if answer.user.profile_picture %>
				<img src="/uploads/<%= answer.user.profile_picture %>" class="profile_image" >
			<%else%>
				<img src="/uploads/twitter-default-no-profile-pic.jpg" class="profile_image" >
			<% end %>
		</div>
		<div class = "right">
		answered by <%=answer.user.firstName%> <%=answer.user.lastName%>
		on <%=answer.created_at.strftime("%b %d,%y")%><br>
		</div>
		</div>
		<h2><%=answer.question.content%></h2><br>
		<%= answer.content%><br>
	</div>
	<%end%>
</div>
	<%end%>
</main>

app/views/home/users.html.erb
<main class="users">
<%users=User.all%>
<h2><%=users.length%> users are available on quora<br><br></h2>
<% users.each do |user|%>
	<div class="user_template">
	<div class="leftPart">
	<span class="left">
	<% if user.profile_picture %>
			<img src="/uploads/<%= user.profile_picture %>" class="profile_image" >
		<%else%>
			<img src="/uploads/twitter-default-no-profile-pic.jpg" class="profile_image" >
		<% end %>
		</span>
		<span class="right">
		<h3><%= link_to "#{user.email}",url_for(controller:'home',action: 'profile',user: user)%></h3>
		</span>
	</div>
	<div class="rightPart">
	<%=link_to user.followed(user.id,current_user.id), url_for(controller: 'home', action: 'follow',followee_id: user.id),remote: true,method: :post,id: "follow_#{user.id}"%>
	 <div class="follow"> followers: <span id="followers_<%=user.id%>"><%=user.followers.length%></span> followings: <span id="followings_<%=user.id%>"><%=user.followings.length%></span></div><br>
	 </div>
	 </div>
<%end%>
</main>